# Generated by Django 3.1 on 2020-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=50)),
                ('LASTNAME', models.CharField(max_length=50)),
                ('DOMAIN', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=50)),
                ('EXPERIENCE', models.IntegerField()),
                ('SALARY', models.IntegerField()),
            ],
            options={
                'verbose_name': 'trainer_info',
                'verbose_name_plural': 'trainer_infos',
            },
        ),
    ]
