# Generated by Django 3.1 on 2020-09-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=50)),
                ('LASTNAME', models.CharField(max_length=50)),
                ('CLG', models.CharField(max_length=50)),
                ('BRANCH', models.CharField(max_length=50)),
                ('CGPA', models.IntegerField()),
            ],
            options={
                'verbose_name': 'student_info',
                'verbose_name_plural': 'student_infos',
            },
        ),
    ]
